service: my-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  createUser:
    handler: src/interfaces/CreateUserController.createUser
    events:
      - http:
          path: users
          method: post
