service: my-lambda-function

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  getItems:
    handler: dist/handlers/getItems.handler
    events:
      - http:
          path: /items
          method: get
