service: my-lambda-function
provider:
  name: aws
  runtime: nodejs14.x

functions:
  createUser:
    handler: dist/interfaces/handlers.createUserHandler
    events:
      - http:
          path: /users
          method: post
  getUser:
    handler: dist/interfaces/handlers.getUserHandler
    events:
      - http:
          path: /users/{id}
          method: get
  updateUser:
    handler: dist/interfaces/handlers.updateUserHandler
    events:
      - http:
          path: /users/{id}
          method: put
  deleteUser:
    handler: dist/interfaces/handlers.deleteUserHandler
    events:
      - http:
          path: /users/{id}
          method: delete

package:
  include:
    - dist/**
