service: hello

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  finance:
    handler: src/hello.handler

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
