service: my-lambda-function
provider:
  name: aws
  runtime: nodejs14.x

functions:
  createUser:
    handler: src/interfaces/handler.createUserHandler
    events:
      - http:
          path: /users
          method: post
  getUser:
    handler: src/interfaces/handler.getUserHandler
    events:
      - http:
          path: /users/{id}
          method: get
  updateUser:
    handler: src/interfaces/handler.updateUserHandler
    events:
      - http:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/interfaces/handler.deleteUserHandler
    events:
      - http:
          path: /users/{id}
          method: delete

package:
  include:
    - dist/**
