Skip to content
Search or jump to…
Pulls
Issues
Codespaces
Marketplace
Explore
 
@JGONZALEZ1432 
jacksonyuan-yt
/
basic-serverless-lambda
Public
Fork your own copy of jacksonyuan-yt/basic-serverless-lambda
Code
Issues
1
Pull requests
1
Actions
Projects
Security
Insights
basic-serverless-lambda/.github/workflows/main.yml
@jacksonyuan-yt
jacksonyuan-yt initial commit
Latest commit b6e328c on Dec 28, 2020
 History
 1 contributor
31 lines (27 sloc)  731 Bytes

name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}