name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v0.1.3
        with:
          function-name: my-lambda-function
          zip-file: dist/index.zip
          handler: handler
          runtime: nodejs14.x
          role: arn:aws:iam::123456789012:role/lambda-execution-role
