name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Package code into ZIP file
        run: zip -r function.zip dist/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync ZIP file to S3
        uses: jakejarvis/s3-sync-action@v2.0.1
        with:
          args: --acl public-read
          source: function.zip
          bucket_url: s3://my-bucket-name

      - name: Deploy Lambda function
        uses: jamesisaac/actions-aws-cli@0.3.0
        with:
          args: lambda update-function-code --function-name my-lambda-function --s3-bucket my-bucket-name --s3-key function.zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
